### ISSUE TITLE
Mouse dpi too high

### ISSUE THREAD

**Issue by RealMrCactus** [mengdeveloper/microsoftrbx-cursor-fix#27]
please optimise your code because i use a really high dpi and i keep tabbing into my other monitor

**Comment by zzahkaboom24** [comment]
Thanks. Will set my mouse dpi rlly high and try to fix it

**Comment by zzahkaboom24** [comment]
Since GitHub doesnt support .rar files in comments.
You may try out this release, or make it yourself from #32 to fix your issue. I have tested it with a high DPI too and I think this approach should fix it fully. If you want the binary its down below until meng gets the PR in. If you wanna build it yourself, feel free.
[x64.CursorFix.zip](https://github.com/mengdeveloper/microsoftrbx-cursor-fix/files/12504306/x64.CursorFix.zip)

**Comment by RealMrCactus** [comment]
> Since GitHub doesnt support .rar files in comments.
> You may try out this release, or make it yourself from #32 to fix your issue. I have tested it with a high DPI too and I think this approach should fix it fully. If you want the binary its down below until meng gets the PR in. If you wanna build it yourself, feel free.
> [x64.CursorFix.zip](https://github.com/mengdeveloper/microsoftrbx-cursor-fix/files/12504306/x64.CursorFix.zip)

Alright thanks
